spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

endpoints:
  aoe:
    user: ""
    match_count: &count=5
    player_match_history: "https://aoe2.net/api/player/matches?game=aoe2de&steam_id="
    player_ranking_history: "https://aoe2.net/api/player/ratinghistory?game=aoe2de&leaderboard_id=4&steam_id="
    player_online_count: "https://aoe2.net/api/stats/players?game=aoe2de"
    return_all_lobbies: "https://aoe2.net/api/lobbies?game=aoe2de"

tmp:
  users:
    jahan: 76561197989421548
    george: 76561198835871299
    ralph: 76561198236126814
    hayden: 76561198080895557
    rus: 76561198048932097

